### ISSUE TITLE
Registering a new game times out and locks thread

### ISSUE THREAD

**Issue by gugi9000** [gugi9000/foosball#21]

**Comment by gugi9000** [comment]
```
POST /newgame/submit application/x-www-form-urlencoded:
    => Matched: POST /newgame/submit
```

**Comment by LFalch** [comment]
I think what's happening is that the thread handling the request locks the database object. As to why it never responds, I'm still looking into.

**Comment by LFalch** [comment]
Found the cause of the issue. Fixing now!
