### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by gugi9000** [gugi9000/foosball#24]
Log web requests and if possible errors (panics) to a file.

**Comment by gugi9000** [comment]
Rocket logs web requests

**Comment by LFalch** [comment]
How wonderful

Få Outlook til iOS<https://aka.ms/o0ukef>



On Sat, Jan 27, 2018 at 6:48 PM +0100, "Bjarke Sørensen" <notifications@github.com<mailto:notifications@github.com>> wrote:


Rocket logs web requests

-

**Comment by gugi9000** [comment]
I suppose a service script should handle crashes..
Panics and 500s should maybe also be handles by 3rd party?
