### ISSUE TITLE
No divider between 3rd and 4th games in /player/<foo>

### ISSUE THREAD

**Issue by gugi9000** [gugi9000/foosball#34]
When listing games for a given player, there is no visual divider between 3rd and 4th game.

![billede](https://user-images.githubusercontent.com/271348/30108528-fcd89052-9302-11e7-8ad2-bc9c1a186952.png)

**Comment by LFalch** [comment]
Does inspecting the element in browser reveal anything about the cause?

**Comment by gugi9000** [comment]
No. Turns out, it was a user fault.

When you browser is set to 90% zoom:

![billede](https://user-images.githubusercontent.com/271348/30418075-0f2c577c-9932-11e7-9ca8-20f5418f93c9.png)
