### ISSUE TITLE
Admin mode

### ISSUE THREAD

**Issue by gugi9000** [gugi9000/foosball#53]
Admin role with ability to

- add/edit players (name, photo)
- add/edit balls (name/photo)
- edit games (everything)
- reset stats (given that it's needed when a games has been edited)

**Comment by LFalch** [comment]
So we want to do the user system then?

**Comment by gugi9000** [comment]
Not necessarily. 
It could just be an admin password - different from the one used to register games.

**Comment by gugi9000** [comment]
Or yes. That's better. #54 is what we want.

Closing because it's a duplicate of #54
